language: cpp

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - valgrind
      - libgtk-3-dev
      - libpango1.0-dev
      - check

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

install:
  - pip install --user --upgrade cmake

script:
  - ctest -VV -S ./ci.ctest

# blocklist
branches:
  except:
    - /^feature.*$/
